---
title: "MCView configuration files "
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{config}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

An __MCView__ project can have 3 configuration files: 

1. config.yaml - main configuration file (required)
2. help.yaml - help text messages (optional)
3. about.Rmd - text for the about tab (optional)

## config.yaml 

This is the main configuration file of the app. It is required both for generating the files the app needs (import) and controlling the app appearance and behavior. 

__MCView__ supports both _metacell1_ (the R package) and _metacell2_ (metacells python package). We are going to focus mainly on import from _metacell2_. See The end of this document for  _metacell1_ import parameters. 

We will start with an example and then go over the parameters one by one: 

```yaml
title: MCView
tabs: ["About", "Manifold", "Genes", "Metacells", "Annotate"] # which tabs to show
help: false # set to true to show introjs help on start
metacells: 
  PBMC:
    anndata: raw/metacells.h5ad # should be absolute path
    cell_type_field: cluster # name of the field in the anndata object$obs which contains a cell type (optional)
    metacell_types: # cell type annotation for each metacell
      fn: raw/metacell-cell-types.csv # file with with cell type assignment for each metacell
      metacell: mc # name of the field which contains the metacell id
      cell_type: cluster # name of the field which contains the cell type      
    cell_type_colors: # color annotation for each cell type
      fn:  raw/cluster-colors.csv # file with color for each cell type (optional)
      cell_type: cluster # name of the field which contains the cell type
      color: color # name of the field which contains the color
# selected_gene1: Foxc1 # Default selected gene1 (optional)
# selected_gene2: Twist1 # Default selected gene2 (optional)
selected_mc1: 1 # Default selected metacell1 
selected_mc2: 2 # Default selected metacell2
```


### title

The title of the app. This would be shown on the top left of the screen. 

### tabs

Controls which tabs to show, and their order. Options are: 

```yaml
["About", "Manifold", "Genes", "Metacells", "Annotate"]
```

### help

Controls wether to start the app with a help modal (from introjs). 

### metacells

A list of one or more metacell dataset. Each dataset should contain at least the `anndata` parameter which holds the path for the `h5ad` file which is the output of metacell2. Switching between the different dataset is done via the right sidebar in the app. 

Dataset parameters: 

#### anndata

Path for for the `h5ad` file which is the output of metacell2. Note that the data should have either absolute path or relative path to the directory from which we run the `import` command. 

#### cell_type_field (optional)

Name of the field in the anndata object$obs which contains a cell type (or a cluster). 

If this parameter and `metacell_types` are missing, __MCView__ would cluster the metacell matrix using kmeans++ algorithm (from the `tglkmeans` package). Note if `metacell_types` parameter is set this field is ignored. 

### metacell_types(optional)

If you already have a cell type assignment (or a cluster assignment) for each metacell, you can use this set of parameters to point __MCView__ to a file which holds this information. 

Parameters are: 

- fn: filename with cell type assignment for each metacell
- metacell: name of the field which contains the metacell id
- cell_type: name of the field which contains the cell type

If this set of parameters and `cell_type_field` are missing, __MCView__ would cluster the metacell matrix using kmeans++ algorithm (from the `tglkmeans` package).

#### cell_type_colors(optional)

Link to a file that holds color assignment for each cell type (or cluster). If this is missing, __MCView__ would use the `chameleon` package to assign cell type colors. 

Parameters are: 

- fn: filename with color assignment for each cell type (or cluster)
- cell_type: name of the field which contains the cell type id
- color: name of the field which contains the color

### selected_gene1/selected_gene2 (optional)

The default genes that would be selected (in any screen with gene selection). If this parameter is missing, the 2 genes with highest max(expr)-min(expr) in the first dataset would be chosen. 

### selected_mc1/selected_mc2

The default metacells that would be selected in the Metacells tab. 

## help.yaml

This file contains the help messages used by introjs. It shouldn't be changed in general, except maybe the introduction message. Note that the messages refer to shiny elements, so you would have to look at the code itself in order to identify the element of each message. 

## about.Rmd

This Rmarkdown file contains the contents of the about page. Edit it as you wish, and remember that you can remove the "About" tab altogether using the `tabs` parameter in `config.yaml`. 

## Metacell1 parameters

The only section that changes when importing from metacell1 is in the dataset parameters. The following example imports a dataset that was generated using R metacell package: 

```yaml
title: MCView
tabs: ["About", "Manifold", "Genes", "Metacells", "Annotate"] # which tabs to show
help: false # set to true to show introjs help on start
datasets: 
  PBMC:
    scdb: scrna_db/ # path to R metacell scrna databse
    matrix: exe_f # name of the umi matrix to use
    mc: exe_f # name of the metacell object to use
    mc2d: exe_f # name of the 2d projection object to use
    network: exe_f # name of the network object to use (optional)
    metacell_types:  # cell type annotation for each metacell 
      fn: metacell_types.tsv # file with with cell type assignment for each metacell
      cell_type: cell_type # name of the field which contains the cell type  
      cell_type_colors: cell_type_colors # name of the field which contains the cell type color
      mc_age: mc_age # age parameter for each metacell (optional)
      metacell: metacell # name of the field which contains the metacell id
    cell_type_colors:   # color annotation for each cell type
      fn: ell_type_annot.tsv # file with color for each cell type (optional)
      cell_type: cell_type # name of the field which contains the cell type
      color: color # name of the field which contains the color
      order: order # name of the field which contains cell type order (optional). Needed mostly for vein plots
    time_annot: # names for the time bins (optional, only relevant with networks/flows)
      fn: time_annot.tsv # name of the file which contains a description (name) for each time bin
      time_bin: time_bin # name of the field which contains the time bin
      time_desc: time_desc # name of the field which contains the description of the time bin
    time_bin_field: exe_f_age_group # name of a filed in cell_metadata which contains time bin per cell (optional)
# selected_gene1: Foxc1 # Default selected gene1 (optional)
# selected_gene2: Twist1 # Default selected gene2 (optional)
selected_mc1: 1 # Default selected metacell1 
selected_mc2: 2 # Default selected metacell2
```