---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",  
  out.width = "100%"
)
```

# MCView

MCView creates a shiny-app facilitating interactive exploration and annotation of metacell models. Metacell itself is described [here](https://pypi.org/project/metacells/).

See more about MCView [here](https://tanaylab.github.io/MCView), report a bug [here](https://github.com/tanaylab/MCView/issues).

## Where to start 

On the left sidebar you will find a list of tabs, click on the tab to open it. See below a short description of each tab.

Additional tabs can be added from the right sidebar which can be opened by clicking on the "Gears" icon at the top right of the screen. Select the tabs you want and then click on "Update Tabs".

## Tabs

#### Main tabs:

- __QC__: View QC metrics of the metacell model.
- __Manifold__: View the 2d projection of the manifold
- __Genes__: Compare gene expression and metadata over the metacells.
- __Diff expression__: Compare metacells / cell types.
- __Markers__: View a heatmap of 'marker genes' over the metacell model. 
- __Cell types__: View gene expression and metadata over cell types.
- __Annotate__: Assign cell types and colors to metacells.
- __Gene modules__: Create gene modules to be used in other tabs.

#### QC tabs: 

- __Inner-fold__
- __Outliers__

#### Atlas projection tabs: 

- __Query__: Examine the results of a projection of the metacell model over an atlas.
- __Atlas__: View the 2d projection of the atlas.
- __Projected-fold__
 
#### Additional tabs:

- __Samples__





