// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// kernel_sanity.cpp
int mcview_sanity_cpp();
extern "C" SEXP _MCView_mcview_sanity_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(mcview_sanity_cpp());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_MCView_mcview_sanity_cpp", (DL_FUNC) &_MCView_mcview_sanity_cpp, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_MCView(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
