# Generated by cpp11: do not edit by hand

mcview_sanity_cpp <- function() {
  .Call(`_MCView_mcview_sanity_cpp`)
}

top_fold_per_col_cpp <- function(fp, k, min_val, fold_reg, use_abs, row_names, col_names) {
  .Call(`_MCView_top_fold_per_col_cpp`, fp, k, min_val, fold_reg, use_abs, row_names, col_names)
}
